<?php
    $helper = $this->helper('Nexio\OnlinePayment\Helper\Data');
    $getCardData = $helper->getSaveCardToken();
?>

<script type="text/javascript">
    window.iHeight    = "<?=$helper->getHeight();?>";
    window.iWidth     = "<?=$helper->getWidth();?>";
    window.sPublicKey = "<?=$helper->getSPublicKey();?>";
    window.baseURL    = "<?=$helper->getVaultUrl();?>";
    const getCardData    = <?=json_encode($getCardData);?>;

</script>
<script type="text/javascript">
require(
    [
        'jquery',
        'Magento_Ui/js/modal/modal','mage/url',
        'Nexio_OnlinePayment/js/vault/validate',
        'mage/translate',
        'domReady!'
    ],
    function($,modal, url,validate,messageList,$t) {
        if ( getCardData && getCardData.length >= 5 ){
            $('#modal-btn').hide();
        }else{
            $('#modal-btn').show();
        }

        $("#modal-btn").click(function () {
            $('body').loader('show');
                var interval = setInterval(
                    function () {
                        if(document.getElementById("iframecontent") != undefined) {
                            const nexioIframe   = document.getElementById("iframecontent").contentWindow.document;
                            var cardholderName  = nexioIframe.getElementById("cardHolderName");    
                            if(cardholderName != undefined) {
                                clearInterval(interval);
                                $('body').loader('hide');
                            }
                        }
                    }, 1000
                );
            $("#iframe_data").show();
            $("#cardsavebutton").show();
            $('#cancelPayment').show();
        });
        
        $("#cardsavebutton").on('click',function(){
           var response = validate.validate();          
        });
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            clickableOverlay: false,
            title: 'Add New Payment',
            buttons: [{
                text: $.mage.__('Cancel'),
                class: 'modal-close',
                click: function (){
                    this.closeModal();
                }
            }]
        };
        modal(options, $('#modal-content'));
        $("#modal-btn").on('click',function(){
            $("#modal-content").modal("openModal");
        });    
        $("#modal-btn").on('click',function(){
            $(".modal-footer").hide();
        });
        $(".action-close").on('click',function(){
            $(".modal-footer").show();
        });
        $("#cancelPayment").on('click',function(){
            $(".modal-footer").show();
        });
    }
);
</script>

<button id="modal-btn" class="action primary">Add Payment</button>
<div id="modal-content">
    <div class="modal-inner-content">
        <div id="iframe_data" class="loader" style="display:none;">
            <iframe title='NexioGroup Payment Method' id='iframecontent' data-bind="attr: {src: baseURL, height: iHeight, width: iWidth}"></iframe>
        </div>
        <input type="hidden" id="cardstatuscheck" value="0"/>
        <div class="cancal-add-payment">
            <button id="cancelPayment" class="modal-close" type="button" data-role="action" style="display:none;"><span>Cancel</span></button>
            
            <button id="cardsavebutton" type="submit" class="action primary" style="display:none;">Add Payment</button>
        </div>
    </div>
</div>
