<script>
    require([
        'jquery',
        'prototype'
    ], function ($) {

        $('#setwebhook_config').click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getUrl('nexio_onlinepayment/webhookconfig/'); ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                showLoader: true,
                onCreate: function () {
					$('body').trigger('processStart');
                    $('#response_message').text('');
                },
                onSuccess: function (transport) {
                    if (transport.responseJSON.message != undefined && transport.responseJSON.message == 'success') {
                        $('#response_message').css("color", "green");
                        $('#response_message').text('Successfully Configured Webhook');

                    } else if (transport.responseJSON.error != undefined && transport.responseJSON.error == '1001') {
                        var message = transport.responseJSON.message;
                        $('#response_message').css("color", "red");
                        $('#response_message').text(message);

                    } else if (transport.responseJSON.message != undefined && transport.responseJSON.message == 'error') {
                        $('#response_message').css("color", "red");
                        $('#response_message').text('Unauthorized Please Check!');

                    }

                	$('body').trigger('processStop');
                    var resultText = '';
                    if (transport.status > 200) {
                        resultText = transport.statusText;
                    } else {
                        var response = JSON.parse(transport.responseText);
                        resultText = response.message
                    }
                }
            });
        });
    });
</script>
<strong ><span id="response_message"></span><br></strong>
<?php echo $block->getButtonHtml(); ?>
