<?php
use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use Magento\Vault\Block\CardRendererInterface;

/** @var CardRendererInterface|Template $block */

$ccNumberView = $block->escapeHtml($block->getNumberLast4Digits());
?>
<tr>
    <td data-th="<?= $block->escapeHtml(__('Card Number')) ?>" class="col card-number">
        <span><?= $block->escapeHtml(__('ending')) ?></span> <?= /* @noEscape */ $ccNumberView ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Expiration Date')) ?>" class="col card-expire">
        <?= $block->escapeHtml($block->getExpDate()) ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Type')) ?>" class="col card-type">
        <img src="<?= /* @noEscape */ $block->getIconUrl() ?>"
             width="<?= /* @noEscape */ $block->getIconWidth() ?>"
             height="<?= /* @noEscape */ $block->getIconHeight() ?>"
        >
    </td>
    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
        <form
            class="form"
            action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
            method="post"
            >
            <?= $block->getBlockHtml('formkey') ?>
            <input
                name="<?= /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
                value="<?= /* @noEscape */ $block->getToken()->getPublicHash() ?>"
                type="hidden"/>
       <?php $cardData = json_decode($block->getToken()->getDetails(),true);
                $cardType = $cardData['card']; ?>
       <?php $break = "<br>";?>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                                    "Magento_Vault/js/customer_account/deleteWidget":{
                                        "type": "popup",
                                        "modalClass": "my-credit-cards-popup",
                                        "toggleEvent": "click",
                                        "title": "Confirm Payment Method Deletion",
                                        "content": "Are you sure you want to delete this payment method?<?= $break ?><?= $cardType ?>&nbsp<?= $block->escapeHtml(__('ending')) ?>&nbsp<?=
                                            /* @noEscape */ $ccNumberView
                                        ?>"
                                    }
                                }'>
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
        <?php if($block->getToken()->getMakeDefault() == 0){ ?>
        <form             
                class="form"
                action="<?= $block->escapeUrl($block->getUrl('onlinepayment/index/makedefault')) ?>"
                method="post">
                <?= $block->getBlockHtml('formkey') ?>
                <input
                    name="<?= /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
                    value="<?= /* @noEscape */ $block->getToken()->getPublicHash() ?>"
                    type="hidden"/>
                <div class="makeDefault">
                <button type="submit" id="make"
                    class="action delete make"
                    data-mage-init='{
                        "Nexio_OnlinePayment/js/customer_account/makeDefaultWidget":{
                            "type": "popup",
                            "modalClass": "my-credit-cards-default-popup",
                            "toggleEvent": "click",
                            "title": "Confirm Default Payment Method",
                            "content": "Are you sure you want to make default this payment method?"
                        }
                    }'>
                    Make Default
                </button> 
                </div>  
        </form>
        <?php } ?>
    </td>
</tr>
<script type="text/javascript">
require(
    [
        'jquery',
        'Magento_Ui/js/modal/modal'
    ],
    function($, modal) {
       
        $(".makeDefault").on('click',function(){
            $(".modal-footer").show();
        });
        $(".action delete").on('click',function(){
            $(".modal-footer").show();
        });
        
    }
);
</script>
